# Generated by Django 4.1.2 on 2023-01-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoToFirebase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='binDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='binTime',
            field=models.CharField(max_length=20),
        ),
    ]
