# Generated by Django 4.1.2 on 2023-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoToFirebase', '0004_alter_smartbin_battery_alter_smartbin_binlevel1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='battery',
            field=models.IntegerField(verbose_name='Battery'),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='binLevel1',
            field=models.IntegerField(verbose_name='Bin Level 1'),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='binLevel2',
            field=models.IntegerField(verbose_name='Bin Level 2'),
        ),
    ]
