# Generated by Django 4.1.2 on 2023-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoToFirebase', '0005_alter_smartbin_battery_alter_smartbin_binlevel1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartbin',
            name='binDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='binTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
